### ISSUE TITLE
package imports (llvmlite, numba, resampy, numpy)

### ISSUE THREAD

**Issue by redhann** [gregoryxie/nicer-rack#17]
Can't run music server due to package import errors, difficulty resolving different package requirements.
```
putz@raspberrypi:/var/www/nicer-rack $ python3 music_server.py
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
Traceback (most recent call last):
  File "/var/www/nicer-rack/music_server.py", line 7, in <module>
    from link_handler import convert_mp3_to_wav
  File "/var/www/nicer-rack/link_handler.py", line 12, in <module>
    import librosa
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/putz/.local/lib/python3.9/site-packages/librosa/util/utils.py", line 5, in <module>
    import scipy.ndimage
  File "/home/putz/.local/lib/python3.9/site-packages/scipy/ndimage/__init__.py", line 151, in <module>
    from ._filters import *  # noqa: F401 F403
  File "/home/putz/.local/lib/python3.9/site-packages/scipy/ndimage/_filters.py", line 37, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import
```

**Comment by redhann** [comment]
pip list
```
Package            Version
------------------ ------------
appdirs            1.4.4
audioread          2.1.9
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.12
decorator          5.1.1
idna               3.3
joblib             1.1.0
llvmlite           0.38.0
numba              0.55.1
numpy              1.22.3
packaging          21.3
Pillow             9.1.0
pip                20.3.4
pkg-resources      0.0.0
pooch              1.6.0
pycparser          2.21
pydub              0.25.1
pyparsing          3.0.8
pytube             12.1.0
requests           2.27.1
resampy            0.2.2
scikit-learn       1.0.2
scipy              1.8.0
setuptools         44.1.1
six                1.16.0
SoundFile          0.10.3.post1
threadpoolctl      3.1.0
urllib3            1.26.9
```
